### ISSUE TITLE
Black action fails

### ISSUE THREAD

**Issue by dariusmargineansrx** [rickstaa/action-black#18]
Hello!

I am using action-black configured in a github action job like this:

```
name: job-name
on:
  push:
    branches: "main"
jobs:
  job-name:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
            steps:
              - name: Black formatter
        uses: rickstaa/action-black@v1
        with:
          black_args: "."
```

However, I saw that it now fails with the next output:

```
[2/3] RUN  python -m venv venv && . venv/bin/activate &&  pip install --upgrade pip && venv/bin/pip install --upgrade --no-cache-dir black:
  20.82       creating build/temp.linux-x86_64-cpython-312
  20.82       creating build/temp.linux-x86_64-cpython-312/multidict
  20.82       gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O3 -Wall -fPIC -I/venv/include -I/usr/local/include/python3.12 -c multidict/_multidict.c -o build/temp.linux-x86_64-cpython-312/multidict/_multidict.o -O2 -std=c99 -Wall -Wsign-compare -Wconversion -fno-strict-aliasing -pedantic
  20.82       error: command 'gcc' failed: No such file or directory
  20.82       [end of output]
  20.82   
  20.82   note: This error originates from a subprocess, and is likely not a problem with pip.
  20.82   ERROR: Failed building wheel for multidict
  20.82 Failed to build frozenlist multidict
  20.82 ERROR: Could not build wheels for frozenlist, multidict, which is required to install pyproject.toml-based projects
  ------
  Dockerfile:6
  --------------------
     4 |         PYTHONUNBUFFERED 1
     5 |     
     6 | >>> RUN  python -m venv venv && . venv/bin/activate &&  pip install --upgrade pip && venv/bin/pip install --upgrade --no-cache-dir black
     7 |     
     8 |     COPY entrypoint.sh /entrypoint.sh
  --------------------
  ERROR: failed to solve: process "/bin/sh -c python -m venv venv && . venv/bin/activate &&  pip install --upgrade pip && venv/bin/pip install --upgrade --no-cache-dir black" did not complete successfully: exit code: 1
 ```
 
 Yesterday (11 Dec 2023), it was working fine. Please, do you have any ideas how can I fix this?
